### ISSUE TITLE
Adapt this project for using in cubbles-coder-devtools for rte@3.x

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx-rename-artifact#2]
Please adapt and test this projekt with cubbles-coder-devtools@3.x. 
For example exist no tag dom-module in elementary html template anymore...

**Comment by edwingamboa** [comment]
After checking skeletons form `cubx-grunt-webpackage-scaffold` for rte 3.0.0, the only difference identified was that elementaries do not use `dom-module`. Thus, the only adaption has to do with that issue.
